// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.0
// source: akkks.proto

package maa

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DummyLista3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dummy []*CheckSet `protobuf:"bytes,1,rep,name=dummy,proto3" json:"dummy,omitempty"`
}

func (x *DummyLista3) Reset() {
	*x = DummyLista3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akkks_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DummyLista3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyLista3) ProtoMessage() {}

func (x *DummyLista3) ProtoReflect() protoreflect.Message {
	mi := &file_akkks_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyLista3.ProtoReflect.Descriptor instead.
func (*DummyLista3) Descriptor() ([]byte, []int) {
	return file_akkks_proto_rawDescGZIP(), []int{0}
}

func (x *DummyLista3) GetDummy() []*CheckSet {
	if x != nil {
		return x.Dummy
	}
	return nil
}

type CheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To   string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akkks_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_akkks_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_akkks_proto_rawDescGZIP(), []int{1}
}

func (x *CheckRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CheckRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type DeleteRequestb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *DeleteRequestb) Reset() {
	*x = DeleteRequestb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akkks_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRequestb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequestb) ProtoMessage() {}

func (x *DeleteRequestb) ProtoReflect() protoreflect.Message {
	mi := &file_akkks_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequestb.ProtoReflect.Descriptor instead.
func (*DeleteRequestb) Descriptor() ([]byte, []int) {
	return file_akkks_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteRequestb) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type GetAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akkks_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_akkks_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_akkks_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CheckSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid            string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	PricePerPerson int32  `protobuf:"varint,2,opt,name=price_per_person,json=pricePerPerson,proto3" json:"price_per_person,omitempty"`
	PriceHole      int32  `protobuf:"varint,3,opt,name=price_hole,json=priceHole,proto3" json:"price_hole,omitempty"`
	NumberOfPeople int32  `protobuf:"varint,4,opt,name=number_of_people,json=numberOfPeople,proto3" json:"number_of_people,omitempty"`
	From           string `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To             string `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *CheckSet) Reset() {
	*x = CheckSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akkks_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSet) ProtoMessage() {}

func (x *CheckSet) ProtoReflect() protoreflect.Message {
	mi := &file_akkks_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSet.ProtoReflect.Descriptor instead.
func (*CheckSet) Descriptor() ([]byte, []int) {
	return file_akkks_proto_rawDescGZIP(), []int{4}
}

func (x *CheckSet) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CheckSet) GetPricePerPerson() int32 {
	if x != nil {
		return x.PricePerPerson
	}
	return 0
}

func (x *CheckSet) GetPriceHole() int32 {
	if x != nil {
		return x.PriceHole
	}
	return 0
}

func (x *CheckSet) GetNumberOfPeople() int32 {
	if x != nil {
		return x.NumberOfPeople
	}
	return 0
}

func (x *CheckSet) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CheckSet) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type PriceAndIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MinPrice int32  `protobuf:"varint,2,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice int32  `protobuf:"varint,3,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
}

func (x *PriceAndIdRequest) Reset() {
	*x = PriceAndIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akkks_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceAndIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceAndIdRequest) ProtoMessage() {}

func (x *PriceAndIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_akkks_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceAndIdRequest.ProtoReflect.Descriptor instead.
func (*PriceAndIdRequest) Descriptor() ([]byte, []int) {
	return file_akkks_proto_rawDescGZIP(), []int{5}
}

func (x *PriceAndIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PriceAndIdRequest) GetMinPrice() int32 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *PriceAndIdRequest) GetMaxPrice() int32 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

type Emptyb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Emptyb) Reset() {
	*x = Emptyb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akkks_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Emptyb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emptyb) ProtoMessage() {}

func (x *Emptyb) ProtoReflect() protoreflect.Message {
	mi := &file_akkks_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emptyb.ProtoReflect.Descriptor instead.
func (*Emptyb) Descriptor() ([]byte, []int) {
	return file_akkks_proto_rawDescGZIP(), []int{6}
}

var File_akkks_proto protoreflect.FileDescriptor

var file_akkks_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x6b, 0x6b, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a,
	0x0b, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x33, 0x12, 0x1f, 0x0a, 0x05,
	0x64, 0x75, 0x6d, 0x6d, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x53, 0x65, 0x74, 0x52, 0x05, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x22, 0x42, 0x0a,
	0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74,
	0x6f, 0x22, 0x22, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x62, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x1f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xb3, 0x01, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x53, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x70,
	0x65, 0x72, 0x5f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x68, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x48, 0x6f, 0x6c, 0x65, 0x12, 0x28,
	0x0a, 0x10, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66, 0x5f, 0x70, 0x65, 0x6f, 0x70,
	0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x4f, 0x66, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x74, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x11,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x41, 0x6e, 0x64, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x6d, 0x61, 0x78, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x08, 0x0a, 0x06, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x62, 0x32, 0x98, 0x02, 0x0a, 0x17, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x76, 0x69, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x12, 0x31, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x0d, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x53, 0x65, 0x74, 0x12, 0x36, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x66, 0x6f,
	0x72, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c,
	0x2e, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x33, 0x12, 0x30, 0x0a, 0x1a,
	0x53, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x41, 0x76, 0x69, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x09, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x53, 0x65, 0x74, 0x1a, 0x07, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x62, 0x12, 0x28,
	0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0f,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x62, 0x1a,
	0x07, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x62, 0x12, 0x36, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x61,
	0x6c, 0x6c, 0x62, 0x79, 0x49, 0x44, 0x61, 0x6e, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12,
	0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x41, 0x6e, 0x64, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x33,
	0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2e, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_akkks_proto_rawDescOnce sync.Once
	file_akkks_proto_rawDescData = file_akkks_proto_rawDesc
)

func file_akkks_proto_rawDescGZIP() []byte {
	file_akkks_proto_rawDescOnce.Do(func() {
		file_akkks_proto_rawDescData = protoimpl.X.CompressGZIP(file_akkks_proto_rawDescData)
	})
	return file_akkks_proto_rawDescData
}

var file_akkks_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_akkks_proto_goTypes = []interface{}{
	(*DummyLista3)(nil),       // 0: DummyLista3
	(*CheckRequest)(nil),      // 1: CheckRequest
	(*DeleteRequestb)(nil),    // 2: DeleteRequestb
	(*GetAllRequest)(nil),     // 3: GetAllRequest
	(*CheckSet)(nil),          // 4: CheckSet
	(*PriceAndIdRequest)(nil), // 5: PriceAndIdRequest
	(*Emptyb)(nil),            // 6: Emptyb
}
var file_akkks_proto_depIdxs = []int32{
	4, // 0: DummyLista3.dummy:type_name -> CheckSet
	1, // 1: AccommodationAviability.GetAccommodationCheck:input_type -> CheckRequest
	3, // 2: AccommodationAviability.GetAllforAccomendation:input_type -> GetAllRequest
	4, // 3: AccommodationAviability.SetAccommodationAviability:input_type -> CheckSet
	2, // 4: AccommodationAviability.DeleteByUser:input_type -> DeleteRequestb
	5, // 5: AccommodationAviability.GetallbyIDandPrice:input_type -> PriceAndIdRequest
	4, // 6: AccommodationAviability.GetAccommodationCheck:output_type -> CheckSet
	0, // 7: AccommodationAviability.GetAllforAccomendation:output_type -> DummyLista3
	6, // 8: AccommodationAviability.SetAccommodationAviability:output_type -> Emptyb
	6, // 9: AccommodationAviability.DeleteByUser:output_type -> Emptyb
	0, // 10: AccommodationAviability.GetallbyIDandPrice:output_type -> DummyLista3
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_akkks_proto_init() }
func file_akkks_proto_init() {
	if File_akkks_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_akkks_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DummyLista3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_akkks_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_akkks_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRequestb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_akkks_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_akkks_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_akkks_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceAndIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_akkks_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Emptyb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_akkks_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_akkks_proto_goTypes,
		DependencyIndexes: file_akkks_proto_depIdxs,
		MessageInfos:      file_akkks_proto_msgTypes,
	}.Build()
	File_akkks_proto = out.File
	file_akkks_proto_rawDesc = nil
	file_akkks_proto_goTypes = nil
	file_akkks_proto_depIdxs = nil
}
